### ISSUE TITLE
Make the attending box better

### ISSUE THREAD

**Issue by mithro** [sydney-linux-user-group/slug#10]
It's actually kinda weird that it shows your gravatar.... Maybe it should just show the gravatars of other people attending or something?

Anyway it need work.

**Comment by jamezpolley** [comment]
Define work..

**Comment by mithro** [comment]
See the email I sent. Am working on it.

**Comment by jamezpolley** [comment]
Complete in 46775bdbf25aec6cc3e7e453bd0996db66a520eb
