### ISSUE TITLE
Fix handling of September

### ISSUE THREAD

**Issue by jamezpolley** [sydney-linux-user-group/slug#50]
Web UI insists on displaying September as "Sept.".

tz_dateparser doesn't know how to handle that, it only knows about "Sep."

**Comment by jamezpolley** [comment]
First stab at a fix in 563f8d82023a9c9c46112ea9c6967e37f6287bf5

**Comment by jamezpolley** [comment]
Fix completed in 7065ffe43ef0ded052af4a85c5e5c897030b1f3d

**Comment by mithro** [comment]
We should really make datetime_tz support parsing Sept. :/

**Comment by jamezpolley** [comment]
Disagree.

Jan Feb Mar Apr Jun Jul Aug Sept Oct Nov Dec <- What's odd about this sequence?

September should be 3 characters, just like the other months.
